name: Test - IT Self-Service Agent

on:
  workflow_dispatch:

concurrency:
  group: quickstart-ci-tests
  cancel-in-progress: false

jobs:
  test:
    name: it-self-service-agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup-and-deploy
        timeout-minutes: 15
        with:
          repo_url: https://github.com/rh-ai-quickstart/it-self-service-agent
          deploy_command: "make helm-install-test"
        env:
          PROD_TOKEN: ${{ secrets.PROD_TOKEN }}
          PROD_SERVER: ${{ secrets.PROD_SERVER }}
          LLM: ${{ vars.LLM_INFERENCE }}
          LLM_ID: ${{ vars.LLM_ID_INFERENCE }}
          LLM_URL: ${{ vars.LLM_URL_INFERENCE }}
          LLM_API_TOKEN: ${{ secrets.LLM_API_TOKEN_INFERENCE }}

      - uses: ./.github/actions/run-quickstart-tests
        timeout-minutes: 30
        with:
          pre_test_command: "curl -LsSf https://astral.sh/uv/0.8.9/install.sh | sh"
          test_command: "make test-short-resp-integration-request-mgr"
        env:
          LLM: ${{ vars.LLM_INFERENCE }}
          LLM_ID: ${{ vars.LLM_ID_INFERENCE }}
          LLM_URL: ${{ vars.LLM_URL_INFERENCE }}
          LLM_API_TOKEN: ${{ secrets.LLM_API_TOKEN_INFERENCE }}

      - uses: ./.github/actions/cleanup
        if: always()
        with:
          cleanup_command: "make helm-uninstall NAMESPACE=$NAMESPACE"
